import { color } from "../common/chess-color"

export const enum PgnNAG {
    null_annotation = "$0",
    good_move = "$1",
    poor_move = "$2",
    very_good_move = "$3",
    very_poor_move = "$4",
    speculative_move = "$5",
    questionable_move = "$6",
    forced_move = "$7",
    singular_move = "$8",
    worst_move = "$9",
    drawish_position = "$10",
    equal_chances_quiet_position = "$11",
    equal_chances_active_position = "$12",
    unclear_position = "$13",
    White_has_a_slight_advantage = "$14",
    Black_has_a_slight_advantage = "$15",
    White_has_a_moderate_advantage = "$16",
    Black_has_a_moderate_advantage = "$17",
    White_has_a_decisive_advantage = "$18",
    Black_has_a_decisive_advantage = "$19",
    White_has_a_crushing_advantage = "$20",
    Black_has_a_crushing_advantage = "$",
    White_is_in_zugzwang = "$22",
    Black_is_in_zugzwang = "$23",
    White_has_a_slight_space_advantage = "$24",
    Black_has_a_slight_space_advantage = "$25",
    White_has_a_moderate_space_advantage = "$26",
    Black_has_a_moderate_space_advantage = "$27",
    White_has_a_decisive_space_advantage = "$28",
    Black_has_a_decisive_space_advantage = "$29",
    White_has_a_slight_time_development_advantage = "$30",
    Black_has_a_slight_time_development_advantage = "$31",
    White_has_a_moderate_time_development_advantage = "$32",
    Black_has_a_moderate_time_development_advantage = "$33",
    White_has_a_decisive_time_development_advantage = "$34",
    Black_has_a_decisive_time_development_advantage = "$35",
    White_has_the_initiative = "$36",
    Black_has_the_initiative = "$37",
    White_has_a_lasting_initiative = "$38",
    Black_has_a_lasting_initiative = "$39",
    White_has_the_attack = "$40",
    Black_has_the_attack = "$41",
    White_has_insufficient_compensation_for_material_deficit = "$42",
    Black_has_insufficient_compensation_for_material_deficit = "$43",
    White_has_sufficient_compensation_for_material_deficit = "$44",
    Black_has_sufficient_compensation_for_material_deficit = "$45",
    White_has_more_than_adequate_compensation_for_material_deficit = "$46",
    Black_has_more_than_adequate_compensation_for_material_deficit = "$47",
    White_has_a_slight_center_control_advantage = "$48",
    Black_has_a_slight_center_control_advantage = "$49",
    White_has_a_moderate_center_control_advantage = "$50",
    Black_has_a_moderate_center_control_advantage = "$51",
    White_has_a_decisive_center_control_advantage = "$52",
    Black_has_a_decisive_center_control_advantage = "$53",
    White_has_a_slight_kingside_control_advantage = "$54",
    Black_has_a_slight_kingside_control_advantage = "$55",
    White_has_a_moderate_kingside_control_advantage = "$56",
    Black_has_a_moderate_kingside_control_advantage = "$57",
    White_has_a_decisive_kingside_control_advantage = "$58",
    Black_has_a_decisive_kingside_control_advantage = "$59",
    White_has_a_slight_queenside_control_advantage = "$60",
    Black_has_a_slight_queenside_control_advantage = "$61",
    White_has_a_moderate_queenside_control_advantage = "$62",
    Black_has_a_moderate_queenside_control_advantage = "$63",
    White_has_a_decisive_queenside_control_advantage = "$64",
    Black_has_a_decisive_queenside_control_advantage = "$65",
    White_has_a_vulnerable_first_rank = "$66",
    Black_has_a_vulnerable_first_rank = "$67",
    White_has_a_well_protected_first_rank = "$68",
    Black_has_a_well_protected_first_rank = "$69",
    White_has_a_poorly_protected_king = "$70",
    Black_has_a_poorly_protected_king = "$71",
    White_has_a_well_protected_king = "$72",
    Black_has_a_well_protected_king = "$73",
    White_has_a_poorly_placed_king = "$74",
    Black_has_a_poorly_placed_king = "$75",
    White_has_a_well_placed_king = "$76",
    Black_has_a_well_placed_king = "$77",
    White_has_a_very_weak_pawn_structure = "$78",
    Black_has_a_very_weak_pawn_structure = "$79",
    White_has_a_moderately_weak_pawn_structure = "$80",
    Black_has_a_moderately_weak_pawn_structure = "$81",
    White_has_a_moderately_strong_pawn_structure = "$82",
    Black_has_a_moderately_strong_pawn_structure = "$83",
    White_has_a_very_strong_pawn_structure = "$84",
    Black_has_a_very_strong_pawn_structure = "$85",
    White_has_poor_knight_placement = "$86",
    Black_has_poor_knight_placement = "$87",
    White_has_good_knight_placement = "$88",
    Black_has_good_knight_placement = "$89",
    White_has_poor_bishop_placement = "$90",
    Black_has_poor_bishop_placement = "$91",
    White_has_good_bishop_placement = "$92",
    Black_has_good_bishop_placement = "$93",
    White_has_poor_rook_placement = "$94",
    Black_has_poor_rook_placement = "$95",
    White_has_good_rook_placement = "$96",
    Black_has_good_rook_placement = "$97",
    White_has_poor_queen_placement = "$98",
    Black_has_poor_queen_placement = "$99",
    White_has_good_queen_placement = "$100",
    Black_has_good_queen_placement = "$101",
    White_has_poor_piece_coordination = "$102",
    Black_has_poor_piece_coordination = "$103",
    White_has_good_piece_coordination = "$104",
    Black_has_good_piece_coordination = "$105",
    White_has_played_the_opening_very_poorly = "$106",
    Black_has_played_the_opening_very_poorly = "$107",
    White_has_played_the_opening_poorly = "$108",
    Black_has_played_the_opening_poorly = "$109",
    White_has_played_the_opening_well = "$110",
    Black_has_played_the_opening_well = "$111",
    White_has_played_the_opening_very_well = "$112",
    Black_has_played_the_opening_very_well = "$113",
    White_has_played_the_middlegame_very_poorly = "$114",
    Black_has_played_the_middlegame_very_poorly = "$115",
    White_has_played_the_middlegame_poorly = "$116",
    Black_has_played_the_middlegame_poorly = "$117",
    White_has_played_the_middlegame_well = "$118",
    Black_has_played_the_middlegame_well = "$119",
    White_has_played_the_middlegame_very_well = "$120",
    Black_has_played_the_middlegame_very_well = "$121",
    White_has_played_the_ending_very_poorly = "$122",
    Black_has_played_the_ending_very_poorly = "$123",
    White_has_played_the_ending_poorly = "$124",
    Black_has_played_the_ending_poorly = "$125",
    White_has_played_the_ending_well = "$126",
    Black_has_played_the_ending_well = "$127",
    White_has_played_the_ending_very_well = "$128",
    Black_has_played_the_ending_very_well = "$129",
    White_has_slight_counterplay = "$130",
    Black_has_slight_counterplay = "$131",
    White_has_moderate_counterplay = "$132",
    Black_has_moderate_counterplay = "$133",
    White_has_decisive_counterplay = "$134",
    Black_has_decisive_counterplay = "$135",
    White_has_moderate_time_control_pressure = "$136",
    Black_has_moderate_time_control_pressure = "$137",
    White_has_severe_time_control_pressure = "$138",
    Black_has_severe_time_control_pressure = "$139",
    With_the_idea = "$140",
    Aimed_against = "$141",
    Better_is = "$142",
    Worse_is = "$143",
    Equivalent_is = "$144",
    Editorial_comment = "$145",
    Novelty = "$146"
}

export const mapAnnotationToNAG: { annotation: string; activeColor?: color; nag: PgnNAG }[] = [
    { annotation: '□', nag: PgnNAG.forced_move },
    { annotation: '[]', nag: PgnNAG.forced_move },
    { annotation: '∞', nag: PgnNAG.unclear_position },
    { annotation: '~~', nag: PgnNAG.equal_chances_quiet_position },
    { annotation: '⩲', nag: PgnNAG.White_has_a_slight_advantage },
    { annotation: '+/=', nag: PgnNAG.White_has_a_slight_advantage },
    { annotation: '⩱', nag: PgnNAG.Black_has_a_slight_advantage },
    { annotation: '=/+', nag: PgnNAG.Black_has_a_slight_advantage },
    { annotation: '±', nag: PgnNAG.White_has_a_moderate_advantage },
    { annotation: '+/-', nag: PgnNAG.White_has_a_moderate_advantage },
    { annotation: '∓', nag: PgnNAG.Black_has_a_moderate_advantage },
    { annotation: '-/+', nag: PgnNAG.Black_has_a_moderate_advantage },
    { annotation: '+-', nag: PgnNAG.White_has_a_decisive_advantage },
    { annotation: '-+', nag: PgnNAG.Black_has_a_decisive_advantage },

    // use activeColor 
    { annotation: '⨀', activeColor: color.white, nag: PgnNAG.White_is_in_zugzwang },
    { annotation: '(.)', activeColor: color.white, nag: PgnNAG.White_is_in_zugzwang },
    { annotation: '⨀', activeColor: color.black, nag: PgnNAG.Black_is_in_zugzwang },
    { annotation: '(.)', activeColor: color.black, nag: PgnNAG.Black_is_in_zugzwang },
    { annotation: '○', activeColor: color.white, nag: PgnNAG.White_has_a_moderate_space_advantage },
    { annotation: '○', activeColor: color.black, nag: PgnNAG.Black_has_a_moderate_space_advantage },
    { annotation: '⟳', activeColor: color.white, nag: PgnNAG.White_has_a_moderate_time_development_advantage },
    { annotation: '@', activeColor: color.white, nag: PgnNAG.White_has_a_moderate_time_development_advantage },
    { annotation: '⟳', activeColor: color.black, nag: PgnNAG.Black_has_a_moderate_time_development_advantage },
    { annotation: '@', activeColor: color.black, nag: PgnNAG.Black_has_a_moderate_time_development_advantage },
    { annotation: '↑', activeColor: color.white, nag: PgnNAG.White_has_the_initiative },
    { annotation: '|^', activeColor: color.white, nag: PgnNAG.White_has_the_initiative },
    { annotation: '↑', activeColor: color.black, nag: PgnNAG.Black_has_the_initiative },
    { annotation: '|^', activeColor: color.black, nag: PgnNAG.Black_has_the_initiative },
    { annotation: '→', activeColor: color.white, nag: PgnNAG.White_has_the_attack },
    { annotation: '->', activeColor: color.white, nag: PgnNAG.White_has_the_attack },
    { annotation: '→', activeColor: color.black, nag: PgnNAG.Black_has_the_attack },
    { annotation: '->', activeColor: color.black, nag: PgnNAG.Black_has_the_attack },
    { annotation: '~/=', activeColor: color.white, nag: PgnNAG.White_has_sufficient_compensation_for_material_deficit },
    { annotation: '~/=', activeColor: color.black, nag: PgnNAG.Black_has_sufficient_compensation_for_material_deficit },
    { annotation: '=/∞', activeColor: color.white, nag: PgnNAG.White_has_more_than_adequate_compensation_for_material_deficit },
    { annotation: '=/∞', activeColor: color.black, nag: PgnNAG.Black_has_more_than_adequate_compensation_for_material_deficit },
    { annotation: '⇆', activeColor: color.white, nag: PgnNAG.White_has_moderate_counterplay },
    { annotation: '<=>', activeColor: color.white, nag: PgnNAG.White_has_moderate_counterplay },
    { annotation: '⇆', activeColor: color.black, nag: PgnNAG.Black_has_moderate_counterplay },
    { annotation: '<=>', activeColor: color.black, nag: PgnNAG.Black_has_moderate_counterplay },
    { annotation: '⨁', activeColor: color.white, nag: PgnNAG.White_has_severe_time_control_pressure },
    { annotation: '(+)', activeColor: color.white, nag: PgnNAG.White_has_severe_time_control_pressure },
    { annotation: '⨁', activeColor: color.black, nag: PgnNAG.Black_has_severe_time_control_pressure },
    { annotation: '(+)', activeColor: color.black, nag: PgnNAG.Black_has_severe_time_control_pressure },
    // special annotations by some PGN Software (none standard)
    { annotation: '∆', nag: PgnNAG.With_the_idea },
    { annotation: '/\\', nag: PgnNAG.With_the_idea },
    { annotation: '∇', nag: PgnNAG.Aimed_against },
    { annotation: '\\/', nag: PgnNAG.Aimed_against },
    { annotation: '⌓', nag: PgnNAG.Better_is },
    { annotation: '>=', nag: PgnNAG.Better_is },
    { annotation: '<=', nag: PgnNAG.Worse_is },
    { annotation: '==', nag: PgnNAG.Equivalent_is },
    { annotation: 'RR', nag: PgnNAG.Editorial_comment },
    { annotation: 'N', nag: PgnNAG.Novelty },
]
