import { CastleFlags, castleType } from './chess-board-king-moves'
import { color } from './chess-color'

describe('Testing chess-board-representation', () => {

    test('testing validation (Rook)', () => {
        let data = new CastleFlags(true, true, true, true)
        let data2 = new CastleFlags(true, true, true, true)
        expect(data.canCastleShortBlack).toBe(true)
        expect(data.canCastleLongBlack).toBe(true)
        expect(data.canCastleShortWhite).toBe(true)
        expect(data.canCastleLongWhite).toBe(true)
        data.noCastle(color.black)
        expect(data.canCastleShortBlack).toBe(false)
        expect(data.canCastleLongBlack).toBe(false)
        expect(data.canCastleShortWhite).toBe(true)
        expect(data.canCastleLongWhite).toBe(true)
        data.set(data2)
        expect(data.canCastleShortBlack).toBe(true)
        expect(data.canCastleLongBlack).toBe(true)
        expect(data.canCastleShortWhite).toBe(true)
        expect(data.canCastleLongWhite).toBe(true)
        data.noCastle(color.white)
        expect(data.canCastleShortBlack).toBe(true)
        expect(data.canCastleLongBlack).toBe(true)
        expect(data.canCastleShortWhite).toBe(false)
        expect(data.canCastleLongWhite).toBe(false)
        data.set(data2)
        expect(data.canCastleShortBlack).toBe(true)
        expect(data.canCastleLongBlack).toBe(true)
        expect(data.canCastleShortWhite).toBe(true)
        expect(data.canCastleLongWhite).toBe(true)
        data.setCastleFlag(color.black, castleType.short, false)
        expect(data.canCastleShortBlack).toBe(false)
        expect(data.canCastleLongBlack).toBe(true)
        expect(data.canCastleShortWhite).toBe(true)
        expect(data.canCastleLongWhite).toBe(true)
        data.set(data2)
        data.setCastleFlag(color.black, castleType.long, false)
        expect(data.canCastleShortBlack).toBe(true)
        expect(data.canCastleLongBlack).toBe(false)
        expect(data.canCastleShortWhite).toBe(true)
        expect(data.canCastleLongWhite).toBe(true)
        data.set(data2)
        data.setCastleFlag(color.white, castleType.short, false)
        expect(data.canCastleShortBlack).toBe(true)
        expect(data.canCastleLongBlack).toBe(true)
        expect(data.canCastleShortWhite).toBe(false)
        expect(data.canCastleLongWhite).toBe(true)
        data.set(data2)
        data.setCastleFlag(color.white, castleType.long, false)
        expect(data.canCastleShortBlack).toBe(true)
        expect(data.canCastleLongBlack).toBe(true)
        expect(data.canCastleShortWhite).toBe(true)
        expect(data.canCastleLongWhite).toBe(false)

    })
})