import { Field, FieldFR } from './Field'
describe('Testing common chess-field', () => {

    test('testing CommonField (set values)', () => {
        let f = Field.fromNotation('a1')
        expect(f.isOnBoard).toBe(true)
        expect(f.file).toBe('a')
        expect(f.rank).toBe(1)
        expect(f.notation).toBe('a1')
        expect(f.fileIdx).toBe(0)
        expect(f.rankIdx).toBe(7)
        expect(f.field063Idx).toBe(56)

        f = Field.fromNotation('h8')
        expect(f.isOnBoard).toBe(true)
        expect(f.file).toBe('h')
        expect(f.rank).toBe(8)
        expect(f.notation).toBe('h8')
        expect(f.fileIdx).toBe(7)
        expect(f.rankIdx).toBe(0)
        expect(f.field063Idx).toBe(7)

        f = Field.fromNotation('h1')
        expect(f.isOnBoard).toBe(true)
        expect(f.file).toBe('h')
        expect(f.rank).toBe(1)
        expect(f.notation).toBe('h1')
        expect(f.fileIdx).toBe(7)
        expect(f.rankIdx).toBe(7)
        expect(f.field063Idx).toBe(63)

        f = Field.fromFR('h', 1)
        expect(f.isOnBoard).toBe(true)
        expect(f.file).toBe('h')
        expect(f.rank).toBe(1)
        expect(f.notation).toBe('h1')
        expect(f.fileIdx).toBe(7)
        expect(f.rankIdx).toBe(7)
        expect(f.field063Idx).toBe(63)

        f = Field.fromN({ file: 'h', rank: 1 })
        expect(f.isOnBoard).toBe(true)
        expect(f.file).toBe('h')
        expect(f.rank).toBe(1)
        expect(f.notation).toBe('h1')
        expect(f.fileIdx).toBe(7)
        expect(f.rankIdx).toBe(7)
        expect(f.field063Idx).toBe(63)

        f = Field.fromI(7, 7)
        expect(f.isOnBoard).toBe(true)
        expect(f.file).toBe('h')
        expect(f.rank).toBe(1)
        expect(f.notation).toBe('h1')
        expect(f.fileIdx).toBe(7)
        expect(f.rankIdx).toBe(7)
        expect(f.field063Idx).toBe(63)

        f = Field.fromFieldIdx({ fileIdx: 7, rankIdx: 7 })
        expect(f.isOnBoard).toBe(true)
        expect(f.file).toBe('h')
        expect(f.rank).toBe(1)
        expect(f.notation).toBe('h1')
        expect(f.fileIdx).toBe(7)
        expect(f.rankIdx).toBe(7)
        expect(f.field063Idx).toBe(63)

        f = Field.fromField063Idx(56)
        expect(f.isOnBoard).toBe(true)
        expect(f.file).toBe('a')
        expect(f.rank).toBe(1)
        expect(f.notation).toBe('a1')
        expect(f.fileIdx).toBe(0)
        expect(f.rankIdx).toBe(7)
        expect(f.field063Idx).toBe(56)

        f = Field.fromField063Idx(63)
        expect(f.isOnBoard).toBe(true)
        expect(f.file).toBe('h')
        expect(f.rank).toBe(1)
        expect(f.fieldN).toMatchObject({ file: 'h', rank: 1 })
        expect(f.notation).toBe('h1')
        expect(f.fileIdx).toBe(7)
        expect(f.rankIdx).toBe(7)
        expect(f.fieldIdx).toMatchObject({ fileIdx: 7, rankIdx: 7 })
        expect(f.field063Idx).toBe(63)
    })

    test('testing CommonField (Error handling)', () => {
        let f = new Field()
        expect(f.isOnBoard).toBe(false)
        expect(() => f.file).toThrowError(Error)
        expect(() => f.rank).toThrowError(Error)
        expect(() => f.fieldN).toThrowError(Error)
        expect(() => f.notation).toThrowError(Error)
        expect(() => f.fileIdx).toThrowError(Error)
        expect(() => f.rankIdx).toThrowError(Error)
        expect(() => f.fieldIdx).toThrowError(Error)
        expect(() => f.field063Idx).toThrowError(Error)

        expect(new Field(8, 1).isOnBoard).toBe(false)
        expect(new Field(-1, 1).isOnBoard).toBe(false)
        expect(new Field(2, -1).isOnBoard).toBe(false)
        expect(new Field(7, 8).isOnBoard).toBe(false)
        expect(Field.fromI(8, 0).isOnBoard).toBe(false)
        expect(Field.fromI(0, 8).isOnBoard).toBe(false)
        expect(Field.fromI(5, -1).isOnBoard).toBe(false)
        expect(Field.fromI(-1, 4).isOnBoard).toBe(false)
        expect(Field.fromField063Idx(64).isOnBoard).toBe(false)
        expect(Field.fromField063Idx(-1).isOnBoard).toBe(false)
    })

    test('testing CommonField (comparing)', () => {
        let f1 = new Field()
        let f2 = new Field()
        expect(() => f1.same(f2)).toThrowError(Error)
        expect(() => f1.sameFR(f2.file, f2.rank)).toThrowError(Error)
        expect(() => f1.sameN(f2.fieldN)).toThrowError(Error)
        expect(() => f1.sameNotation(f2.notation)).toThrowError(Error)
        expect(() => f1.sameI(f2.fileIdx, f2.rankIdx)).toThrowError(Error)
        expect(() => f1.sameIdx(f2.fieldIdx)).toThrowError(Error)
        expect(() => f1.same063I(f2.field063Idx)).toThrowError(Error)

        f2 = Field.fromNotation('d4')
        expect(() => f1.same(f2)).toThrowError(Error)
        expect(() => f1.sameFR(f2.file, f2.rank)).toThrowError(Error)
        expect(() => f1.sameN(f2.fieldN)).toThrowError(Error)
        expect(() => f1.sameNotation(f2.notation)).toThrowError(Error)
        expect(() => f1.sameI(f2.fileIdx, f2.rankIdx)).toThrowError(Error)
        expect(() => f1.sameIdx(f2.fieldIdx)).toThrowError(Error)
        expect(() => f1.same063I(f2.field063Idx)).toThrowError(Error)

        f1 = Field.fromNotation('d4')
        f2 = new Field()
        expect(f1.same(f2)).toBe(false)
        expect(() => f1.sameFR(f2.file, f2.rank)).toThrowError(Error)
        expect(() => f1.sameN(f2.fieldN)).toThrowError(Error)
        expect(() => f1.sameNotation(f2.notation)).toThrowError(Error)
        expect(() => f1.sameI(f2.fileIdx, f2.rankIdx)).toThrowError(Error)
        expect(() => f1.sameIdx(f2.fieldIdx)).toThrowError(Error)
        expect(() => f1.same063I(f2.field063Idx)).toThrowError(Error)

        f1 = Field.fromNotation('d4')
        f2 = new Field(f1.fileIdx, f1.rankIdx)
        expect(f1.same(f2)).toBe(true)
        expect(f1.sameFR(f2.file, f2.rank)).toBe(true)
        expect(f1.sameN(f2.fieldN)).toBe(true)
        expect(f1.sameNotation(f2.notation)).toBe(true)
        expect(f1.sameI(f2.fileIdx, f2.rankIdx)).toBe(true)
        expect(f1.sameIdx(f2.fieldIdx)).toBe(true)
        expect(f1.same063I(f2.field063Idx)).toBe(true)

        f1 = Field.fromNotation('a1')
        f2 = Field.fromNotation('a1')
        expect(f1.same(f2)).toBe(true)
        expect(f1.sameFR(f2.file, f2.rank)).toBe(true)
        expect(f1.sameN(f2.fieldN)).toBe(true)
        expect(f1.sameNotation(f2.notation)).toBe(true)
        expect(f1.sameI(f2.fileIdx, f2.rankIdx)).toBe(true)
        expect(f1.sameIdx(f2.fieldIdx)).toBe(true)
        expect(f1.same063I(f2.field063Idx)).toBe(true)
        f1 = Field.fromNotation('a1')
        f2 = Field.fromNotation('a2')
        expect(f1.same(f2)).toBe(false)
        expect(f1.sameFR(f2.file, f2.rank)).toBe(false)
        expect(f1.sameN(f2.fieldN)).toBe(false)
        expect(f1.sameNotation(f2.notation)).toBe(false)
        expect(f1.sameI(f2.fileIdx, f2.rankIdx)).toBe(false)
        expect(f1.sameIdx(f2.fieldIdx)).toBe(false)
        expect(f1.same063I(f2.field063Idx)).toBe(false)

        f1 = Field.fromNotation('a1')
        f2 = Field.fromField063Idx(56)
        expect(f1.same(f2)).toBe(true)
        expect(f1.sameFR(f2.file, f2.rank)).toBe(true)
        expect(f1.sameN(f2.fieldN)).toBe(true)
        expect(f1.sameNotation(f2.notation)).toBe(true)
        expect(f1.sameI(f2.fileIdx, f2.rankIdx)).toBe(true)
        expect(f1.sameIdx(f2.fieldIdx)).toBe(true)
        expect(f1.same063I(f2.field063Idx)).toBe(true)
        f1 = Field.fromNotation('a1')
        f2 = Field.fromField063Idx(54)
        expect(f1.same(f2)).toBe(false)
        expect(f1.sameFR(f2.file, f2.rank)).toBe(false)
        expect(f1.sameN(f2.fieldN)).toBe(false)
        expect(f1.sameNotation(f2.notation)).toBe(false)
        expect(f1.sameI(f2.fileIdx, f2.rankIdx)).toBe(false)
        expect(f1.sameIdx(f2.fieldIdx)).toBe(false)
        expect(f1.same063I(f2.field063Idx)).toBe(false)

        f1 = Field.fromNotation('a1')
        f2 = Field.fromI(0, 7)
        expect(f1.same(f2)).toBe(true)
        expect(f1.sameFR(f2.file, f2.rank)).toBe(true)
        expect(f1.sameN(f2.fieldN)).toBe(true)
        expect(f1.sameNotation(f2.notation)).toBe(true)
        expect(f1.sameI(f2.fileIdx, f2.rankIdx)).toBe(true)
        expect(f1.sameIdx(f2.fieldIdx)).toBe(true)
        expect(f1.same063I(f2.field063Idx)).toBe(true)
        f1 = Field.fromNotation('a1')
        f2 = Field.fromI(0, 6)
        expect(f1.same(f2)).toBe(false)
        expect(f1.sameFR(f2.file, f2.rank)).toBe(false)
        expect(f1.sameN(f2.fieldN)).toBe(false)
        expect(f1.sameNotation(f2.notation)).toBe(false)
        expect(f1.sameI(f2.fileIdx, f2.rankIdx)).toBe(false)
        expect(f1.sameIdx(f2.fieldIdx)).toBe(false)
        expect(f1.same063I(f2.field063Idx)).toBe(false)

    })

    test('testing CommonFieldFR (set values)', () => {
        let f = FieldFR.fromNotation('a1')
        expect(f.isOnBoard).toBe(true)
        expect(f.file).toBe('a')
        expect(f.rank).toBe(1)
        expect(f.notation).toBe('a1')
        expect(f.fileIdx).toBe(0)
        expect(f.rankIdx).toBe(7)
        expect(f.field063Idx).toBe(56)

        f = FieldFR.fromNotation('h8')
        expect(f.isOnBoard).toBe(true)
        expect(f.file).toBe('h')
        expect(f.rank).toBe(8)
        expect(f.notation).toBe('h8')
        expect(f.fileIdx).toBe(7)
        expect(f.rankIdx).toBe(0)
        expect(f.field063Idx).toBe(7)

        f = FieldFR.fromNotation('h1')
        expect(f.isOnBoard).toBe(true)
        expect(f.file).toBe('h')
        expect(f.rank).toBe(1)
        expect(f.notation).toBe('h1')
        expect(f.fileIdx).toBe(7)
        expect(f.rankIdx).toBe(7)
        expect(f.field063Idx).toBe(63)

        f = FieldFR.fromFieldIdx(7, 7)
        expect(f.isOnBoard).toBe(true)
        expect(f.file).toBe('h')
        expect(f.rank).toBe(1)
        expect(f.notation).toBe('h1')
        expect(f.fileIdx).toBe(7)
        expect(f.rankIdx).toBe(7)
        expect(f.field063Idx).toBe(63)

        f = FieldFR.fromField063Idx(56)
        expect(f.isOnBoard).toBe(true)
        expect(f.file).toBe('a')
        expect(f.rank).toBe(1)
        expect(f.notation).toBe('a1')
        expect(f.fileIdx).toBe(0)
        expect(f.rankIdx).toBe(7)
        expect(f.field063Idx).toBe(56)

        f = FieldFR.fromField063Idx(63)
        expect(f.isOnBoard).toBe(true)
        expect(f.file).toBe('h')
        expect(f.rank).toBe(1)
        expect(f.fieldN).toMatchObject({ file: 'h', rank: 1 })
        expect(f.notation).toBe('h1')
        expect(f.fileIdx).toBe(7)
        expect(f.rankIdx).toBe(7)
        expect(f.fieldIdx).toMatchObject({ fileIdx: 7, rankIdx: 7 })
        expect(f.field063Idx).toBe(63)
    })

    test('testing CommonFieldFR (Error handling)', () => {
        let f = new FieldFR()
        expect(f.isOnBoard).toBe(false)
        expect(() => f.file).toThrowError(Error)
        expect(() => f.rank).toThrowError(Error)
        expect(() => f.fieldN).toThrowError(Error)
        expect(() => f.notation).toThrowError(Error)
        expect(() => f.fileIdx).toThrowError(Error)
        expect(() => f.rankIdx).toThrowError(Error)
        expect(() => f.fieldIdx).toThrowError(Error)
        expect(() => f.field063Idx).toThrowError(Error)

        expect(new FieldFR('x', 1).isOnBoard).toBe(false)
        expect(new FieldFR('A', 1).isOnBoard).toBe(false)
        expect(new FieldFR('2', 1).isOnBoard).toBe(false)
        expect(new FieldFR('e', 0).isOnBoard).toBe(false)
        expect(new FieldFR('e', 9).isOnBoard).toBe(false)
        expect(FieldFR.fromFieldIdx(8, 0).isOnBoard).toBe(false)
        expect(FieldFR.fromFieldIdx(0, 8).isOnBoard).toBe(false)
        expect(FieldFR.fromFieldIdx(5, -1).isOnBoard).toBe(false)
        expect(FieldFR.fromFieldIdx(-1, 4).isOnBoard).toBe(false)
        expect(FieldFR.fromField063Idx(64).isOnBoard).toBe(false)
        expect(FieldFR.fromField063Idx(-1).isOnBoard).toBe(false)
    })

    test('testing CommonFieldFR (comparing)', () => {
        let f1 = new FieldFR()
        let f2 = new FieldFR()
        expect(() => f1.same(f2)).toThrowError(Error)
        expect(() => f1.sameFR(f2.file, f2.rank)).toThrowError(Error)
        expect(() => f1.sameN(f2.fieldN)).toThrowError(Error)
        expect(() => f1.sameNotation(f2.notation)).toThrowError(Error)
        expect(() => f1.sameI(f2.fileIdx, f2.rankIdx)).toThrowError(Error)
        expect(() => f1.sameIdx(f2.fieldIdx)).toThrowError(Error)
        expect(() => f1.same063I(f2.field063Idx)).toThrowError(Error)

        f2 = FieldFR.fromNotation('d4')
        expect(() => f1.same(f2)).toThrowError(Error)
        expect(() => f1.sameFR(f2.file, f2.rank)).toThrowError(Error)
        expect(() => f1.sameN(f2.fieldN)).toThrowError(Error)
        expect(() => f1.sameNotation(f2.notation)).toThrowError(Error)
        expect(() => f1.sameI(f2.fileIdx, f2.rankIdx)).toThrowError(Error)
        expect(() => f1.sameIdx(f2.fieldIdx)).toThrowError(Error)
        expect(() => f1.same063I(f2.field063Idx)).toThrowError(Error)

        f1 = FieldFR.fromNotation('d4')
        f2 = new FieldFR()
        expect(f1.same(f2)).toBe(false)
        expect(() => f1.sameFR(f2.file, f2.rank)).toThrowError(Error)
        expect(() => f1.sameN(f2.fieldN)).toThrowError(Error)
        expect(() => f1.sameNotation(f2.notation)).toThrowError(Error)
        expect(() => f1.sameI(f2.fileIdx, f2.rankIdx)).toThrowError(Error)
        expect(() => f1.sameIdx(f2.fieldIdx)).toThrowError(Error)
        expect(() => f1.same063I(f2.field063Idx)).toThrowError(Error)

        f1 = FieldFR.fromNotation('d4')
        f2 = new FieldFR(f1.file, f1.rank)
        expect(f1.same(f2)).toBe(true)
        expect(f1.sameFR(f2.file, f2.rank)).toBe(true)
        expect(f1.sameN(f2.fieldN)).toBe(true)
        expect(f1.sameNotation(f2.notation)).toBe(true)
        expect(f1.sameI(f2.fileIdx, f2.rankIdx)).toBe(true)
        expect(f1.sameIdx(f2.fieldIdx)).toBe(true)
        expect(f1.same063I(f2.field063Idx)).toBe(true)

        f1 = FieldFR.fromNotation('a1')
        f2 = FieldFR.fromNotation('a1')
        expect(f1.same(f2)).toBe(true)
        expect(f1.sameFR(f2.file, f2.rank)).toBe(true)
        expect(f1.sameN(f2.fieldN)).toBe(true)
        expect(f1.sameNotation(f2.notation)).toBe(true)
        expect(f1.sameI(f2.fileIdx, f2.rankIdx)).toBe(true)
        expect(f1.sameIdx(f2.fieldIdx)).toBe(true)
        expect(f1.same063I(f2.field063Idx)).toBe(true)
        f1 = FieldFR.fromNotation('a1')
        f2 = FieldFR.fromNotation('a2')
        expect(f1.same(f2)).toBe(false)
        expect(f1.sameFR(f2.file, f2.rank)).toBe(false)
        expect(f1.sameN(f2.fieldN)).toBe(false)
        expect(f1.sameNotation(f2.notation)).toBe(false)
        expect(f1.sameI(f2.fileIdx, f2.rankIdx)).toBe(false)
        expect(f1.sameIdx(f2.fieldIdx)).toBe(false)
        expect(f1.same063I(f2.field063Idx)).toBe(false)

        f1 = FieldFR.fromNotation('a1')
        f2 = FieldFR.fromField063Idx(56)
        expect(f1.same(f2)).toBe(true)
        expect(f1.sameFR(f2.file, f2.rank)).toBe(true)
        expect(f1.sameN(f2.fieldN)).toBe(true)
        expect(f1.sameNotation(f2.notation)).toBe(true)
        expect(f1.sameI(f2.fileIdx, f2.rankIdx)).toBe(true)
        expect(f1.sameIdx(f2.fieldIdx)).toBe(true)
        expect(f1.same063I(f2.field063Idx)).toBe(true)
        f1 = FieldFR.fromNotation('a1')
        f2 = FieldFR.fromField063Idx(54)
        expect(f1.same(f2)).toBe(false)
        expect(f1.sameFR(f2.file, f2.rank)).toBe(false)
        expect(f1.sameN(f2.fieldN)).toBe(false)
        expect(f1.sameNotation(f2.notation)).toBe(false)
        expect(f1.sameI(f2.fileIdx, f2.rankIdx)).toBe(false)
        expect(f1.sameIdx(f2.fieldIdx)).toBe(false)
        expect(f1.same063I(f2.field063Idx)).toBe(false)

        f1 = FieldFR.fromNotation('a1')
        f2 = FieldFR.fromFieldIdx(0, 7)
        expect(f1.same(f2)).toBe(true)
        expect(f1.sameFR(f2.file, f2.rank)).toBe(true)
        expect(f1.sameN(f2.fieldN)).toBe(true)
        expect(f1.sameNotation(f2.notation)).toBe(true)
        expect(f1.sameI(f2.fileIdx, f2.rankIdx)).toBe(true)
        expect(f1.sameIdx(f2.fieldIdx)).toBe(true)
        expect(f1.same063I(f2.field063Idx)).toBe(true)
        f1 = FieldFR.fromNotation('a1')
        f2 = FieldFR.fromFieldIdx(0, 6)
        expect(f1.same(f2)).toBe(false)
        expect(f1.sameFR(f2.file, f2.rank)).toBe(false)
        expect(f1.sameN(f2.fieldN)).toBe(false)
        expect(f1.sameNotation(f2.notation)).toBe(false)
        expect(f1.sameI(f2.fileIdx, f2.rankIdx)).toBe(false)
        expect(f1.sameIdx(f2.fieldIdx)).toBe(false)
        expect(f1.same063I(f2.field063Idx)).toBe(false)
    })
})